import streamlit as st
import subprocess
import os
import time
import json
import pandas as pd
import glob

st.set_page_config(page_title="Quant Trading Dashboard", layout="wide", initial_sidebar_state="expanded")

st.title("📈 Live Quantitative Trading Dashboard")
st.markdown("Monitor and control your trading algorithms for NSE Stocks.")

# --- Side panel for controls ---
st.sidebar.header("⚙️ Architecture Engine")

# Start/Stop Engine logic
if "engine_process" not in st.session_state:
    st.session_state.engine_process = None

def start_engine():
    if st.session_state.engine_process is None:
        venv_python = os.path.join("venv", "Scripts", "python.exe") if os.name == "nt" else os.path.join("venv", "bin", "python")
        if not os.path.exists(venv_python):
            venv_python = "python"  # Fallback
            
        st.session_state.engine_process = subprocess.Popen(
            [venv_python, "main.py"],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1
        )
        st.sidebar.success("Engine started successfully!")

def stop_engine():
    if st.session_state.engine_process is not None:
        st.session_state.engine_process.terminate()
        st.session_state.engine_process = None
        st.sidebar.warning("Engine stopped!")

col1, col2 = st.sidebar.columns(2)
with col1:
    if st.button("▶️ Start Engine", type="primary"):
        start_engine()
with col2:
    if st.button("⏹️ Stop Engine"):
        stop_engine()

st.sidebar.divider()
st.sidebar.subheader("System Status")
if st.session_state.engine_process is None:
    st.sidebar.error("Engine is OFFLINE")
else:
    st.sidebar.success("Engine is RUNNING")

# --- Main Dashboard ---
st.header("⚡ Real-Time ML Predictions")
st.markdown("Latest signals generated by the quantitative models.")

signals_path = os.path.join("data", "latest_signals.json")

# Create a placeholder to auto-refresh the metrics
metric_placeholder = st.empty()

# Create a placeholder for charts
chart_placeholder = st.empty()

# Auto Refresh loop (for live app feel)
if st.session_state.engine_process is not None:
    # We use a short sleep & rerun to continuously pull the json files
    time.sleep(1)

if os.path.exists(signals_path):
    try:
        with open(signals_path, "r") as f:
            signals = json.load(f)
        
        if signals:
            cols = metric_placeholder.columns(len(signals))
            for i, (symbol, data) in enumerate(signals.items()):
                pred = data["prediction"]
                # Color code the prediction
                if pred == "BUY":
                    pred_str = f"🟢 BUY"
                elif pred == "SELL":
                    pred_str = f"🔴 SELL"
                else:
                    pred_str = f"⚪ HOLD/SELL"

                with cols[i]:
                    st.metric(
                        label=f"{symbol} Signal",
                        value=pred_str,
                        delta=f"Confidence: {data['confidence']}",
                        delta_color="normal" if pred == "BUY" else "inverse" if pred == "SELL" else "off"
                    )
                    st.caption(f"Last updated: {data['timestamp']}")
        else:
            metric_placeholder.info("Waiting for models to evaluate the streams...")
    except Exception as e:
        metric_placeholder.error(f"Error parsing signals: {e}")
else:
    metric_placeholder.info("No trading signals generated yet. Start the Engine to begin predicting.")

st.divider()

# --- Market Data Chart ---
st.header("📊 Market Data Streaming")
st.markdown("Visualizing the recent processed market data.")
data_dir = os.path.join("data", "processed")
if os.path.exists(data_dir):
    csv_files = glob.glob(os.path.join(data_dir, "*_cleaned.csv"))
    if csv_files:
        symbols = [os.path.basename(f).split('_')[0] for f in csv_files]
        selected_symbol = st.selectbox("Select Asset to View", symbols)
        
        file_path = os.path.join(data_dir, f"{selected_symbol}_5m_cleaned.csv")
        try:
            df = pd.read_csv(file_path, index_col=0, parse_dates=True)
            if not df.empty:
                # Show last 100 periods
                st.line_chart(df['close'].tail(150))
            else:
                st.warning(f"No valid data in {selected_symbol}")
        except Exception as e:
            st.error(f"Error reading chart data: {e}")
    else:
        st.warning("No processed market data available yet.")


# Trigger re-evaluation if the engine is running
if st.session_state.engine_process is not None:
    st.rerun()
